import pandas as pd
import random

data = pd.read_csv("/Users/rickvillanueva/Documents/Myron/dated_random.csv")

data.head()

random_data = data.MYRON_ACCT

#Gathering random account numbers
random.choice(random_data)
random.choice(random_data)
random.choice(random_data)
random.choice(random_data)
random.choice(random_data)
random.choice(random_data)
random.choice(random_data)
random.choice(random_data)
random.choice(random_data)
random.choice(random_data)
random.choice(random_data)
random.choice(random_data)
random.choice(random_data)
random.choice(random_data)
random.choice(random_data)
random.choice(random_data)
random.choice(random_data)
random.choice(random_data)
random.choice(random_data)
random.choice(random_data)
random.choice(random_data)
random.choice(random_data)
random.choice(random_data)
random.choice(random_data)
random.choice(random_data)
random.choice(random_data)
random.choice(random_data)
random.choice(random_data)
random.choice(random_data)
random.choice(random_data)
random.choice(random_data)
random.choice(random_data)
random.choice(random_data)
random.choice(random_data)
random.choice(random_data)
random.choice(random_data)
random.choice(random_data)
random.choice(random_data)
random.choice(random_data)
random.choice(random_data)
random.choice(random_data)
random.choice(random_data)
random.choice(random_data)
random.choice(random_data)
random.choice(random_data)
random.choice(random_data)
random.choice(random_data)
random.choice(random_data)
random.choice(random_data)
random.choice(random_data)


